version: '3'

services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./frontend
    container_name: realworld-docker-frontend
    restart: unless-stopped
    command: serve -s build -l 3000
    expose:
      - 3000:3000
    networks:
      - realworld-docker-network
  
  nginx:
    image: nginx:stable-alpine
    container_name: realworld-docker-nginx
    ports:
      - "800:800"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
    networks:
      - realworld-docker-network

      
networks:
  realworld-docker-network:
    driver: bridge