// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: category.sql

package db

import (
	"context"
)

const createCategory = `-- name: CreateCategory  :one
INSERT INTO fl_category (name) VALUES ($1) RETURNING id, name, created_at, updated_at
`

type CreateCategoryParams struct {
	Name    string     `json:"name"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategoryByIDs = `-- name: DeleteCategoryByIDs :exec
DELETE FROM fl_category WHERE id = $1
`

type DeleteCategoryByIDsParams struct {
	ID       int64 `json:"id"`
}

func (q *Queries) DeleteCategoryByIDs(ctx context.Context, arg DeleteCategoryByIDsParams) error {
	_, err := q.db.Exec(ctx, deleteCategoryByIDs, arg.ID)
	return err
}

const findCategoryByIDs = `-- name: FindCategoryByIDs :one
SELECT id, name, created_at, updated_at FROM fl_category WHERE  id = $1 LIMIT 1
`

type FindCategoryByIDsParams struct {
	ID       int64 `json:"id"`
}

func (q *Queries) FindCategoryByIDs(ctx context.Context, arg FindCategoryByIDsParams) (Category, error) {
	row := q.db.QueryRow(ctx, findCategoryByIDs, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategorys = `-- name: getCategorys :many
SELECT id, name, created_at, updated_at FROM fl_category ORDER BY id DESC
`

func (q *Queries) GetCategorys(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategorys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,	
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory:one
UPDATE fl_category SET name = $3,  updated_at = NOW() WHERE id = $1  RETURNING id, name, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID       int64  `json:"id"`
	Name 	string  `json:"name"`

}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
	)
	var i Category
	err := row.Scan(
		&i.ID,
			&i.Name,	
			&i.CreatedAt,
			&i.UpdatedAt,
	)
	return i, err
}
