// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateCategoryValue(ctx context.Context, arg CreateCategoryValueParams) (CategoryValue, error)
	CreateCoache(ctx context.Context, name string) (Coache, error)
	CreateReset(ctx context.Context, arg CreateResetParams) (Reset, error)
	CreateScoreScale(ctx context.Context, arg CreateScoreScaleParams) (ScoreScale, error)
	CreateSportSchool(ctx context.Context, name string) (SportSchool, error)
	CreateSportsman(ctx context.Context, arg CreateSportsmanParams) (Sportsman, error)
	CreateTournament(ctx context.Context, arg CreateTournamentParams) (Tournament, error)
	CreateTypeTournament(ctx context.Context, name string) (TypeTournament, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategoryByIDs(ctx context.Context, id int64) error
	DeleteCategoryValueByIDs(ctx context.Context, id int64) error
	DeleteCoacheByIDs(ctx context.Context, id int64) error
	DeleteResetsForUser(ctx context.Context, userID int64) error
	DeleteScoreScaleByIDs(ctx context.Context, id int64) error
	DeleteSportSchoolByIDs(ctx context.Context, id int64) error
	DeleteSportsmanByIDs(ctx context.Context, id int64) error
	DeleteTournamentByIDs(ctx context.Context, id int64) error
	DeleteTypeTournamentByIDs(ctx context.Context, id int64) error
	FindCategoryByIDs(ctx context.Context, id int64) (Category, error)
	FindCategoryValueByIDs(ctx context.Context, id int64) (FindCategoryValueByIDsRow, error)
	FindCoacheByIDs(ctx context.Context, id int64) (Coache, error)
	FindResetByCode(ctx context.Context, code string) (Reset, error)
	FindScoreScaleByIDs(ctx context.Context, id int64) (FindScoreScaleByIDsRow, error)
	FindSportSchoolByIDs(ctx context.Context, id int64) (SportSchool, error)
	FindSportsmanByIDs(ctx context.Context, id int64) (FindSportsmanByIDsRow, error)
	FindTournamentByIDs(ctx context.Context, id int64) (FindTournamentByIDsRow, error)
	FindTypeTournamentByIDs(ctx context.Context, id int64) (TypeTournament, error)
	FindUserByEmail(ctx context.Context, lower string) (User, error)
	FindUserByID(ctx context.Context, id int64) (User, error)
	FindUserByVerificationCode(ctx context.Context, verification string) (User, error)
	GetCategoryValues(ctx context.Context) ([]GetCategoryValuesRow, error)
	GetCategorys(ctx context.Context, name string) ([]Category, error)
	GetCoaches(ctx context.Context, name string) ([]Coache, error)
	GetScoreScales(ctx context.Context) ([]GetScoreScalesRow, error)
	GetSportSchools(ctx context.Context, name string) ([]SportSchool, error)
	GetSportsmans(ctx context.Context) ([]GetSportsmansRow, error)
	GetTournaments(ctx context.Context) ([]GetTournamentsRow, error)
	GetTypeTournaments(ctx context.Context, name string) ([]TypeTournament, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCategoryValue(ctx context.Context, arg UpdateCategoryValueParams) (CategoryValue, error)
	UpdateCoache(ctx context.Context, arg UpdateCoacheParams) (Coache, error)
	UpdateScoreScale(ctx context.Context, arg UpdateScoreScaleParams) (ScoreScale, error)
	UpdateSportSchool(ctx context.Context, arg UpdateSportSchoolParams) (SportSchool, error)
	UpdateSportsman(ctx context.Context, arg UpdateSportsmanParams) (Sportsman, error)
	UpdateTournament(ctx context.Context, arg UpdateTournamentParams) (Tournament, error)
	UpdateTypeTournament(ctx context.Context, arg UpdateTypeTournamentParams) (TypeTournament, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
