// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {

	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	DeleteCategoryByIDs(ctx context.Context, arg DeleteCategoryByIDsParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	FindCategoryByIDs(ctx context.Context, arg FindCategoryByIDsParams) (Category, error)
	GetCategorys(ctx context.Context) ([]Category, error)
	

	CreateReset(ctx context.Context, arg CreateResetParams) (Reset, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteResetsForUser(ctx context.Context, userID int64) error
	FindResetByCode(ctx context.Context, code string) (Reset, error)
	FindUserByEmail(ctx context.Context, lower string) (User, error)
	FindUserByID(ctx context.Context, id int64) (User, error)
	FindUserByVerificationCode(ctx context.Context, verification string) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
